### PR TITLE
Mitigated duplication bug

### PR DESCRIPTION
**Pull request by Baarsgaard**
A friend of mine found a duplication bug almost as soon as he tried the mod.

It only happens on SMP due to what seems to be server delay as I could not trigger it offline.

#### Reproduction steps:
1. Hold a shulker in your main-/off-hand
2. Look at a non-interactive block (Anything without right-click functionality)
3. Open inventory and open the shulker with right-click inside the inventory.
4. If the shulker was placed: Take something out and close the screen.
5. Open the placed shulker and see that the item you removed earlier is still present in the shulker despite removing it in the previous screen.

#### What's happening:
On step 3, when you open the shulker. The delay will cause you to place the shulker on the block you're looking at as the right click carries over when cancelling the inventory screen.
The game then proceeds to open the inventory of the shulker and placing the shulker down at the same time.
As soon as the shulker is placed the connection to the item in your inventory is broken, and any modifications will not happen to the shulker placed in the world.

#### The fix:
I have added a 2-step condition that.
If you're looking at a block AND you're holding a shulker in either your main- or off-hand, it will not open.

I used to have just the "Shulker in hand" check, but that ended up being quite disruptive to my gameplay with the mod.

The fix is currently used by my friends on our own server and it seems to be running with no crashes. 

PS:
You're free to modify this implementation as much as you want as I am not a Java developer, I just needed a fix and thought it would be interesting to attempt Java for once. Love the mod :)

### CODE REVIEW

**Comment by kyrptonaught** [comment]
Nice fix, thank you for this. I think this fix is on the client end though? Meaning a user could just not update their mod and still play on servers and abuse the dupe. I'll try to migrate this to be a server side check

**Comment by kyrptonaught** [comment]
Pretty late response, but this was a very good solution to this. I have implemented this serverside in 1.3.10

**Comment by Baarsgaard** [comment]
Glad to hear that, thanks for the update!

**Comment by Baarsgaard** [comment]
On another note:
The same friend of mine had a similar issue while holding blank maps. As they could be activated when you right-click a shulker, essentially wasting the map.
A check for that too, might be useful. At least till the intercept on the right click is figured out.

**Pull request closed without merging**
