### PR TITLE
Add OptiGUI support

### LINKED ISSUE #19: Quick Shulker compatibility
When opening Shulkerboxes in your inventory, via Quick Shulker, they have the default shulker gui colour, instead of their corresponding color. (using Colorful Containers)

https://github.com/kyrptonaught/quickshulker/issues/59#issue-1348588998

### LINKED ISSUE #59: Small issue with OptiGUI
When using a coloured Shulker GUI Resourcepack with OptiGUI, the background of Shulkerboxes opened from the hotbar or the inventory doesn't update. 
It is the background of the last placed down Shulkerbox, the player opened.

It would serve as a great visual indicator for what shulkerbox you just opened, when having many in the inventory.

### PR DESCRIPTION
**Pull request by opekope2**
## What works

* Pressing the hotkey (but not inside the inventory, this needs a change in OptiGUI)

## To be implemented

* [x] Right click support
  * This is tricky because `UseItemCallback` is processed server-side. Probably needs a client-side hook as well
* [x] Support in-inventory quick shulker (needs a change in OptiGUI)

## To be changed (maybe)

* Null safety?

## To be discussed

* Add OptiGUI as a required or an optional dependency (now: required)
  * If optional, it needs a wrapper code
* `Services.getService()` throws if service is not found. The services used by the code are registered by OptiGUI

---

Closes #59
Closes opekope2/OptiGUI-Next#19

### CODE REVIEW

**Comment by opekope2** [comment]
The code is ready for review and discussion.

**Comment by kyrptonaught** [comment]
Thanks for this! 

I'll look over everything soon.

I would prefer this to be an optional dependency, not required. I can do that part though.

**Comment by opekope2** [comment]
A note about the code: it relies on packets sent in order, and `MinecraftClient.execute` is invoked in order (which are the case for the current Minecraft codebase)

**Comment by opekope2** [comment]
Now OptiGUI is an optional dependency. You may decide to include it in "suggests" or "recommends". And yes, I tested it without OptiGUI and it didn't crash with `ClassNotFoundException`.
I'm not quite finished with OptiGUI docs, so I implemented the optional dependency stuff, because I know how my mod works.
Additionally, if you want to test it, make sure to download [Fabric language Kotlin](https://modrinth.com/mod/fabric-language-kotlin) to `run/mods`, and extract the jars from OptiGUI jar to the `run/mods` folder in the project (commons-text and the appropriate optiglue is enough), because loom does something and otherwise you'll get a juicy "Error loading OptiGlue!" exception.

**Comment by opekope2** [comment]
OptiGUI 2.0.0-beta.4 will introduce breaking change. I'll rewrite the code once OptiGUI 2.0.0 full release arrives, and open a new PR. Which will take some time.

**Comment by opekope2** [comment]
After the breaking change in OptiGUI 2.1.0-beta.1, the code has shrunk in size. I have updated the code.

Notes:
* OptiGUI 2.1.0-beta.1 requires Fabric Loader 0.14.19, so I had to edit `gradle.properties`
* Nested JARs need to be extracted into `run/mods`
* A full build probably needs to be issued before running the client, otherwise OptiGUI may not load because of some dependency having the wrong version
* Added a code to check the minimum OptiGUI version

To be discussed:
* Add Fabric Language Kotlin as `modLocalRuntime` into `build.gradle` so it gets downloaded automatically?
* Log something if OptiGUI is too old, so the user can see it?

**Comment by kyrptonaught** [comment]
Can you port this to 1.20/.1? I'll do another look over then

**Comment by opekope2** [comment]
Not in the next two weeks, I'm having some time off coding and I may refactor OptiGUI again after that. I'll open another PR on the 1.20 branch when ready

**Pull request closed without merging**
